examples/web-wagmi/src/components/header/Header.tsx, examples/web-wagmi/src/publications/components/PostComposer.tsx, packages/domain/src/entities/Transactions.ts, packages/domain/src/entities/__helpers__/mocks.ts, packages/react/src/ErrorHandler.tsx, packages/react/src/feed/useFeed.ts, packages/react/src/helpers.ts, packages/react/src/shared.tsx, packages/react/src/transactions/adapters/ProtocolCallRelayer.ts, packages/react/src/transactions/adapters/PublicationCallGateway.ts, packages/react/src/transactions/adapters/TransactionQueuePresenter.tsx, packages/react/src/transactions/adapters/__tests__/PublicationCallGateway.spec.ts, packages/react/src/transactions/adapters/responders/CreatePostResponder.ts, packages/react/src/transactions/adapters/responders/__tests__/CreatePostResponder.spec.ts, packages/react/src/transactions/adapters/useCreatePostController.ts, packages/react/src/transactions/infrastructure/TransactionObserver.ts, packages/react/src/transactions/useCreatePost.ts, packages/react/src/wallet/adapters/ConnectionErrorPresenter.tsx
Changes
- Removes `txHash` from `TransactionError`. This was unused, occasionally `undefined` and source of confusion. The failure is anyway presented with the original Request Model object and if broadcasted the `txHash` so we have plenty of data to report to the user if need to.
- Adds rollback logic in case the tx fails
- Manages scenarios in which the Publication Metadata upload fails. This returns (wrapped in a `FailedUploadError`) back to the `useCreatePost` as `error` the developer can use to diagnose the issue and/or inform the user.
=> feat: improvements on `useCreatePost` optimistic update logic

.changeset/modern-timers-suffer.md, examples/web-wagmi/src/components/auth/LoginButton.tsx, examples/web-wagmi/src/components/auth/auth.tsx, examples/web-wagmi/src/misc/UseNotifications.tsx, examples/web-wagmi/src/misc/UseUnreadNotificationCount.tsx, examples/web-wagmi/src/profiles/UseFollowAndUnfollow.tsx, examples/web-wagmi/src/publications/UseCreateComment.tsx, examples/web-wagmi/src/publications/UseCreateMirror.tsx, examples/web-wagmi/src/publications/UseCreatePost.tsx, examples/web-wagmi/src/publications/UseReaction.tsx, packages/react/src/transactions/useFollow.ts, packages/react/src/wallet/adapters/ActiveWalletPresenter.ts, packages/react/src/wallet/index.ts, packages/react/src/wallet/useActiveWallet.ts
It also aligns `useActiveWallet` to what `useActiveProfile` waits for.
=> fix: fixes flash of logged-out content from example app

.changeset/rotten-candles-teach.md, examples/web-wagmi/src/profiles/ProfilesPage.tsx, examples/web-wagmi/src/revenue/UseProfileFollowRevenue.tsx, examples/web-wagmi/src/revenue/components/RevenueCard.tsx, packages/api-bindings/codegen-api.yml, packages/api-bindings/src/apollo/createApolloCache.ts, packages/api-bindings/src/apollo/createRevenueAggregateTypePolicy.ts, packages/api-bindings/src/graphql/ClientErc20Amount.ts, packages/api-bindings/src/graphql/__helpers__/fragments.ts, packages/api-bindings/src/graphql/client.graphql, packages/api-bindings/src/graphql/generated.tsx, packages/api-bindings/src/graphql/revenue.graphql
This PR extracts the excellent work done by @JoaquinBattilana in this PR: https://github.com/lens-protocol/lens-sdk/pull/76 so it's mergeable with most recent `main` changes.
It focused those changes to address just the `RevenueAggregate.totalAmount: Amount<Erc20>` local-only field.
It basically avoids changes to instances of `ModuleFeeAmount` simply because it make sense to be tackle as part of a new client scalar `FollowPolicy`  which will be taken care by @reecejohnson in https://github.com/lens-protocol/lens-sdk/pull/85.
=> feat: added RevenueAggregate.totalAmount: Amount<Erc20>

examples/web-wagmi/src/App.tsx, examples/web-wagmi/src/profiles/ProfilesPage.tsx, examples/web-wagmi/src/profiles/UseMutualFollowers.tsx, examples/web-wagmi/src/profiles/UseProfileByHandle.tsx, examples/web-wagmi/src/profiles/UseProfileById.tsx, examples/web-wagmi/src/profiles/UseProfileFollowers.tsx, examples/web-wagmi/src/profiles/UseProfileFollowing.tsx, examples/web-wagmi/src/profiles/components/ProfileFollowers.tsx, examples/web-wagmi/src/profiles/components/ProfileFollowing.tsx, examples/web-wagmi/src/profiles/components/ProfileSelector.tsx, examples/web-wagmi/src/revenue/UseProfileFollowRevenue.tsx, examples/web-wagmi/src/revenue/UseProfilePublicationRevenue.tsx, examples/web-wagmi/src/revenue/UsePublicationRevenue.tsx, packages/api-bindings/src/apollo/createApolloCache.ts, packages/api-bindings/src/apollo/createProfileFollowersFieldPolicy.ts, packages/api-bindings/src/apollo/createProfileFollowingFieldPolicy.ts, packages/api-bindings/src/apollo/createProfilePublicationRevenueFieldPolicy.ts, packages/api-bindings/src/graphql/generated.tsx, packages/api-bindings/src/graphql/revenue.graphql, packages/react/src/revenue/useProfilePublicationRevenue.ts
- fixed `useProfileFollowers` to support infinite scroll
- fixed `useProfileFollowing` to support infinite scroll
- fixed `useProfilePublicationRevenue` to work and support infinite scroll
- Refactored example app profile selectors to have less code and be less error-prone (e.g. the `default` string returned from callback where id or handle was expected)
=> bug: followers following queries are missing field policy that allows infinite scroll

packages/api-bindings/src/graphql/__helpers__/fragments.ts, packages/api-bindings/src/graphql/generated.tsx, packages/api-bindings/src/graphql/profile.graphql
Checked the network response of Profile within wagmi, and the additional properties are present:
```
"onChainIdentity": {
"proofOfHumanity": true,
"ens": {
"name": "yoginth.eth",
"__typename": "EnsOnChainIdentity"
},
"sybilDotOrg": {
"verified": true,
"source": {
"twitter": {
"handle": "yogicodes",
"__typename": "SybilDotOrgTwitterIdentity"
},
"__typename": "SybilDotOrgIdentitySource"
},
"__typename": "SybilDotOrgIdentity"
},
"worldcoin": {
"isHuman": false,
"__typename": "WorldcoinIdentity"
},
"__typename": "OnChainIdentity"
},
```
=> feat: surface onChainIdentity

packages/react/src/transactions/useFollow.ts
I'm from [nosociallab](https://github.com/nosocialxyz). During our development with lens api, we found something weird about the follow policy. I assume this is a bug fix. 😄
=> feat: Allow other followPolicy instead of "unknown"

package.json, turbo.json
the number of packages and examples is growing, as devs we don't need to rebuild examples when working, so this PR introduces a new turbo script to rebuild only packages
=> chore: allow to build packages separately

packages/api-bindings/codegen-api.yml, packages/api-bindings/src/graphql/__helpers__/fragments.ts, packages/api-bindings/src/graphql/client.graphql, packages/api-bindings/src/graphql/common.graphql, packages/api-bindings/src/graphql/gated.graphql, packages/api-bindings/src/graphql/generated.tsx, packages/api-bindings/src/graphql/utils/publication.ts
The idea is that `publication.isGated` and `publication.canObserverDecrypt` can and should be used by the consumer to determine if the observer profile can decrypt the content and if not why so.
The `publication.metadata.__encryptionParams` is not fully type safe as it is. In the following PR I will provide a new field (a local-inly field akin to `FollowPolicy` for `__followModule` or `CollectPolicy` for `__collectModule`) that is more straightforward to use an more importantly type safe. The design of this object is effectively a DSL describing the access criteria. This will inform how the `CreatePostRequest` and `CreateCommetnRequest` request models will change to support creation of gated content.
=> featu: adds GQL fragments to fetch gated content details

.github/dependabot.yml
this is a simple dependabot config, if it won't work for monorepo, then we have to configure each directory separately, as in the example
but first we have to merge https://github.com/lens-protocol/lens-sdk/pull/171
=> chore: enable dependabot T-1334

packages/client/TODO.md, packages/client/src/LensClient.ts, packages/client/src/explore/graphql/explore.generated.ts, packages/client/src/feed/graphql/feed.generated.ts, packages/client/src/graphql/fragments.generated.ts, packages/client/src/graphql/fragments.graphql, packages/client/src/graphql/types.generated.ts, packages/client/src/publication/Publication.spec.ts, packages/client/src/publication/Publication.ts, packages/client/src/publication/graphql/publication.generated.ts, packages/client/src/publication/graphql/publication.graphql, packages/client/src/publication/helpers/buildReportReason.ts, packages/client/src/publication/index.ts, packages/client/src/revenue/graphql/revenue.generated.ts
=> feat: client sdk - add publication mutations

.changeset/config.json, README.md
I'm not really happy or just confused with how `changesets` work, as it always bumps major versions even if I requested only minor ones. anyway, with this PR I'm excluding `client` and other packages we don't publish from the changeset versioning to make it a bit easier for the person who prepares the release.
wdyt?
=> chore: update changesets config

examples/web-wagmi/src/profiles/UseCreateProfile.tsx, examples/web-wagmi/src/revenue/UsePublicationRevenue.tsx, packages/api-bindings/src/graphql/__helpers__/fragments.ts, packages/api-bindings/src/graphql/__helpers__/queries.ts, packages/api-bindings/src/graphql/generated.tsx, packages/api-bindings/src/graphql/revenue.graphql, packages/react/src/profile/__tests__/useProfile.spec.ts, packages/react/src/publication/__tests__/useExplorePublications.spec.ts, packages/react/src/publication/__tests__/useProfilePublicationsForSale.spec.ts, packages/react/src/publication/__tests__/usePublication.spec.ts, packages/react/src/publication/__tests__/usePublications.spec.ts, packages/react/src/publication/__tests__/useSearchPublications.spec.ts, packages/react/src/publication/__tests__/useWhoCollectedPublication.spec.ts, packages/react/src/publication/__tests__/useWhoMirroredPublication.spec.ts, packages/react/src/publication/__tests__/useWhoReacted.spec.ts, packages/react/src/publication/useComments.ts, packages/react/src/publication/useExplorePublications.ts, packages/react/src/publication/useProfilePublicationsForSale.ts, packages/react/src/publication/usePublication.ts, packages/react/src/publication/usePublications.ts, packages/react/src/publication/useSearchPublications.ts, packages/react/src/publication/useWhoCollectedPublication.ts, packages/react/src/publication/useWhoMirroredPublication.ts, packages/react/src/publication/useWhoReacted.ts, packages/react/src/revenue/__tests__/useProfilePublicationRevenue.spec.ts, packages/react/src/revenue/__tests__/usePublicationRevenue.spec.ts, packages/react/src/revenue/useProfileFollowRevenue.ts, packages/react/src/revenue/useProfilePublicationRevenue.ts, packages/react/src/revenue/usePublicationRevenue.ts
Following the approach used in the previous PR this PR covers the following hooks:
- `usePublicationRevenue`
- `useProfilePublicationRevenue`
- `useWhoReacted`
- `useWhoMirroredPublication`
- `useWhoCollectedPublication`
- `useSearchPublications`
- `usePublications`
- `usePublication`
- `useProfilePublicationsForSale`
- `useExplorePublications`
- `useComments`
It also refactors `useProfileFollowRevenue` to use new hook helpers.
=> feat: wires Active Profile ID as `observerId` in the remaining hooks

packages/api-bindings/src/apollo/cache/createApolloCache.ts
https://www.apollographql.com/docs/react/caching/cache-configuration/#resultcaching
=> chore: remove `resultCaching` in apollo config because its true by default

packages/domain/src/use-cases/publications/__helpers__/mocks.ts, packages/react/src/transactions/adapters/publication-call-gateways/__tests__/utils.spec.ts
While developing my changes I noticed that this test was not fully testing resolving of collect module for `CreateCommentRequest` but also was giving me issue with TS typedef as I made changes to the request models.
This PR just isolates a refactoring of the existing tests, some rewording, and also extends it to `CreateCommentRequest`.
This just isolates these changes from the following PR.
=> refactor: generalizes `resolveCollectModule` helper tests ahead of `CreateCommentRequest` changes

.changeset/chilled-games-push.md, packages/domain/src/use-cases/lifecycle/Bootstrap.ts, packages/domain/src/use-cases/lifecycle/__tests__/Bootstrap.spec.ts, packages/domain/src/use-cases/profile/ActiveProfileLoader.ts, packages/domain/src/use-cases/profile/IActiveProfilePresenter.ts, packages/domain/src/use-cases/profile/SwitchActiveProfile.ts, packages/domain/src/use-cases/profile/__tests__/ActiveProfileLoader.spec.ts, packages/domain/src/use-cases/wallets/WalletLogin.ts, packages/domain/src/use-cases/wallets/WalletLogout.ts, packages/domain/src/use-cases/wallets/__tests__/WalletLogin.spec.ts, packages/react/src/lifecycle/adapters/useBootstrapController.ts, packages/react/src/profile/adapters/ActiveProfilePresenter.ts, packages/react/src/wallet/adapters/useWalletLoginController.ts, packages/react/src/wallet/index.ts, packages/react/src/wallet/useWalletLogin.ts
This PR shuffles the logic a little bit to present the wallet and profile at the same time otherwise ui state in inconsistent and implementation of the claiming flow is trickier/buggy.
Also `useWalletLogin` now returns `WalletLoginResult` with the wallet and profile to allow imperative redirect call when someone needs it.
=> Present wallet and profile at the same time during login flow.

.changeset/mighty-balloons-shop.md, packages/domain/src/use-cases/wallets/WalletLogin.ts, packages/react/src/profile/useActiveProfile.ts
This is just a patch fix for now, created the ticket to track the proper change on the use case levels https://avara.height.app/T-12199.
=> Require an active profile to have active wallet

packages/react/src/lifecycle/adapters/useBootstrapController.ts, packages/react/src/shared.tsx, packages/react/src/wallet/adapters/WalletGateway.ts, packages/react/src/wallet/adapters/useWalletLoginController.ts, packages/react/src/wallet/adapters/useWalletLogoutController.ts
I was able to trigger the token expiry event by modifying refreshToken stored in local storage and changing its `exp` value. Also setting `AccessTokenStorage.getAccessToken` to always return `''`, to trigger the token refresh.
The logout and storage cleanup proceeded as expected.
Seems everything works fine now!
=> feat: use CredentialsExpiryController and subscribe to expired event

.changeset/slow-glasses-study.md, examples/web-wagmi/src/inbox/UseConversation.tsx, examples/web-wagmi/src/inbox/UseConversations.tsx, examples/web-wagmi/src/inbox/components/ConversationCard.tsx, examples/web-wagmi/src/inbox/components/ConversationComposer.tsx, examples/web-wagmi/src/inbox/components/EnableConversationsButton.tsx, packages/react-web/inbox/package.json, packages/react-web/package.json, packages/react-web/src/index.ts
Given that XMTP is an optional dependencies there should not be codepaths from the main Lens SDK entry point that requires the XMTP SDK.
This PR exposes XMTP integration API from a dedicated entry point. Documentation will be updated once 1.3 becomes stable.
=> fix: makes XMTP SDK optional by not importing it from SDK main entrypoint

.changeset/shy-pugs-taste.md, packages/client/src/LensClient.ts, packages/client/src/context.ts, packages/client/src/helpers/buildImageTransformsFromConfig.ts, packages/client/src/helpers/buildRequestFromConfig.ts, packages/client/src/helpers/requireAuthHeaders.spec.ts, packages/client/src/helpers/sdkAuthHeaderWrapper.spec.ts, packages/client/src/submodules/profile/types.ts
forApps was not doing what was described in the config, forApps has to be provided as part of a request object in each query
=> client: remove forApps from config to avoid confusion

.changeset/smooth-ties-roll.md, examples/web/src/misc/UseNotifications.tsx, examples/web/src/profiles/ProfilesPage.tsx, examples/web/src/profiles/UseFollowAndUnfollow.tsx, examples/web/src/profiles/UseOwnedHandles.tsx, examples/web/src/profiles/UseProfileActionHistory.tsx, examples/web/src/profiles/UseSetProfileMetadata.tsx, examples/web/src/profiles/UseUpdateFollowPolicy.tsx, examples/web/src/profiles/UseUpdateProfileManagers.tsx, examples/web/src/publications/UseBookmarkToggle.tsx, examples/web/src/publications/UseHidePublication.tsx, examples/web/src/publications/UseMyBookmarks.tsx, examples/web/src/publications/UseNotInterestedToggle.tsx, examples/web/src/publications/UseReactionToggle.tsx, packages/api-bindings/src/apollo/cache/transactions.ts, packages/api-bindings/src/apollo/cache/type-policies/createProfileTypePolicy.ts, packages/api-bindings/src/lens/__helpers__/fragments.ts, packages/domain/src/use-cases/profile/LinkHandle.ts, packages/domain/src/use-cases/profile/UnlinkHandle.ts, packages/domain/src/use-cases/profile/__helpers__/mocks.ts, packages/react/src/shared.tsx, packages/react/src/transactions/adapters/profiles/LinkHandleGateway.ts, packages/react/src/transactions/adapters/profiles/UnlinkHandleGateway.ts, packages/react/src/transactions/adapters/profiles/__tests__/LinkHandleGateway.spec.ts, packages/react/src/transactions/adapters/profiles/__tests__/UnlinkHandleGateway.spec.ts, packages/react/src/transactions/adapters/responders/LinkHandleResponder.ts, packages/react/src/transactions/adapters/schemas/profiles.ts, packages/react/src/transactions/useLinkHandle.ts, packages/react/src/transactions/useUnlinkHandle.ts
- API error when unlinking not-linked handle is not propagated to the `error` returned from hook
- solved with preventing submitting a mutation that could cause API error
- API should include more data in the response from `ownedHandles` to build meaningful UI https://avara.height.app/T-17101 
- done
- add an optimistic update
- done
- figure out why updateProfileCache doesn't include new handle
- done
=> react: enable useLinkHandle and useUnlinkHandle hooks

examples/node/scripts/authentication/authenticate.ts, examples/web/src/LogInPage.tsx, packages/react/src/authentication/useLogin.ts
that's all that I found that mentions usage of profiles (ownedBy) query to get profiles before logging in.
=> chore: update examples to use profilesManaged for login

examples/web/src/LogInPage.tsx
Add handling for errors that are thrown by the `useConnect` hook from `wagmi` in the example web app.
=> fix: handle wagmi connection rejection in example web app

.changeset/olive-spiders-pull.md, packages/client/src/errors.ts
```ts
import { GraphQLClientError } from '@lens-protocol/client'
try {
await client.follow(...)
await doSomeThingElse()
} catch (error) {
if (error instanceof Error) {
if (error instanceof GraphQLClientError) {
// handle client error.
}
// handle other error.
}
}
```
=> chore: re-export ClientError as GraphQLClientError

.changeset/forty-horses-speak.md, packages/api-bindings/src/apollo/cache/createTypePolicies.ts, packages/api-bindings/src/apollo/cache/field-policies/createProfileFieldPolicy.ts
when I try to read a profile by a handle in the field policy, I'm getting an apollo error, this could be because of react strict mode
```ts
if (args.request?.forHandle) {
const profile = cache.readQuery({
query: ProfileDocument,
variables: variables,
});
console.log('profile', profile);
}
```
=> react: enable profile field policy

.changeset/thirty-apes-hear.md, packages/cli/package.json, packages/client/package.json
issue: https://github.com/lens-protocol/lens-sdk/issues/966
=> chore: bump node engine upper limit to support new LTS

.changeset/thirty-experts-tell.md, packages/client/src/ethers/signer.ts
Found an issue that is preventing me from sending sponsored transactions because the `customData` contents are being destructured into the root of the TransactionLike object, instead of inside of `TransactionLike::customData`.
=> fix: correctly destructure customData in client's ethers' signWith function
