TODO.md

- Updates TODO hook names and completed stauts

chore: update hooks todo

---

.changeset/cyan-plums-approve.md
TODO.md
examples/web-wagmi/src/App.tsx
examples/web-wagmi/src/publications/PublicationsPage.tsx
examples/web-wagmi/src/publications/UseWhoReacted.tsx
packages/api-bindings/src/apollo/createWhoReactedPublicationFieldPolicy.ts
packages/api-bindings/src/apollo/index.ts
packages/api-bindings/src/graphql/__helpers__/fragments.ts
packages/api-bindings/src/graphql/__helpers__/queries.ts
packages/api-bindings/src/graphql/follow-typed-data.graphql
packages/api-bindings/src/graphql/generated.tsx
packages/api-bindings/src/graphql/reactions.graphql
packages/react/src/publication/__tests__/useWhoReacted.spec.ts
packages/react/src/publication/index.ts
packages/react/src/publication/useWhoReacted.ts

implement `useWhoReacted` hook with an example and test
documentation https://docs.lens.xyz/docs/cyan-plums-approve-usewhoreacted

feat: implement `useWhoReacted` hook (T-293)

---

.changeset/lovely-pets-talk.md

Adds changeset for previous unfollow PR.

chore: add unfollow changeset

---

examples/web-wagmi/src/profiles/UseFollowAndUnfollow.tsx
packages/domain/src/use-cases/profile/UnfollowProfile.ts
packages/react/src/transactions/adapters/useUnfollowController.ts
packages/react/src/transactions/useFollow.ts
packages/react/src/transactions/useUnfollow.ts

- Adds optimistic update of UI for follow
- Adds defence in `useUnfollow` hook is a profile is only optimistically following another and attempts to unfollow

feat: optimistic updates and defence for follow/unfollow

---

.changeset/lemon-turkeys-behave.md
examples/web-wagmi/src/App.tsx
examples/web-wagmi/src/revenue/RevenuePage.tsx
examples/web-wagmi/src/revenue/UseProfilePublicationRevenue.tsx
examples/web-wagmi/src/revenue/components/PublicationRevenueCard.tsx
packages/api-bindings/src/graphql/__helpers__/queries.ts
packages/api-bindings/src/graphql/generated.tsx
packages/api-bindings/src/graphql/revenue.graphql
packages/react/src/revenue/__tests__/useProfilePublicationRevenue.spec.ts
packages/react/src/revenue/index.ts
packages/react/src/revenue/useProfilePublicationRevenue.ts

- Added docs: https://docs.lens.xyz/docs/use-profile-publication-revenue

Add useProfilePublicationRevenue hook

---

examples/web-wagmi/src/revenue/components/PublicationRevenueCard.tsx

I accidentally merged an example in with outdated code and this PR fixes that.

Fix component in examples

---

.github/workflows/ci.yaml
README.md
package.json
packages/domain/src/use-cases/publications/types.ts
pnpm-lock.yaml

- adds `pnpm-deduplicate`
- fixes the duplicated packages reported by `pnpm-deduplicate`

Fix duplicated dependencies

---

packages/api-bindings/src/graphql/__helpers__/mutations.ts
packages/domain/src/use-cases/publications/__helpers__/mocks.ts
packages/react/src/publication/adapters/__tests__/ReportPublicationGateway.spec.ts

PR #80 was merged, but it was missing the last thing, tests for ReportPublicationGateway.
I added them in this PR, but one test is not working as expected and I can't figure out why.
See comments below.

chore: add tests for ReportPublicationGateway

---

.changeset/kind-forks-applaud.md
packages/api-bindings/src/apollo/createExplorePublicationsFieldPolicy.ts
packages/api-bindings/src/apollo/createFeedFieldPolicy.ts
packages/api-bindings/src/apollo/createPublicationsFieldPolicy.ts
packages/api-bindings/src/graphql/comments.graphql
packages/api-bindings/src/graphql/feed.graphql
packages/api-bindings/src/graphql/generated.tsx
packages/api-bindings/src/graphql/publications.graphql
packages/react/src/feed/__tests__/useFeed.spec.ts
packages/react/src/feed/useFeed.ts
packages/react/src/publication/__tests__/filters.spec.ts
packages/react/src/publication/filters.ts
packages/react/src/publication/index.ts
packages/react/src/publication/useComments.ts
packages/react/src/publication/useExplorePublications.ts
packages/react/src/publication/usePublications.ts

feat: formalisation of publication filters

---

packages/shared-kernel/src/crypto/Amount.ts
packages/shared-kernel/src/crypto/__tests__/Amount.spec.ts

* add subtraction and division methods
* add tests

feat: add additional utility methods to Amount

---

packages/react/src/feed/FeedEventItemType.ts
packages/react/src/feed/__tests__/useFeed.spec.ts
packages/react/src/feed/index.ts
packages/react/src/feed/useFeed.ts

https://avara.height.app/T-5148

Restrict FeedItemEventType

---

examples/web-wagmi/src/publications/UseReaction.tsx
packages/api-bindings/src/graphql/__helpers__/fragments.ts
packages/api-bindings/src/graphql/common.graphql
packages/api-bindings/src/graphql/generated.tsx
packages/react/src/publication/adapters/ReactionPresenter.ts
packages/react/src/publication/adapters/__tests__/ReactionPresenter.spec.ts

https://avara.height.app/T-4999

Add ability to add downvotes (Missing reaction type)

---

packages/client/src/LensClient.spec.ts
packages/client/src/LensClient.ts
packages/client/src/index.ts
packages/client/src/search/Search.spec.ts
packages/client/src/search/Search.ts
packages/client/src/search/graphql/search.generated.ts
packages/client/src/search/graphql/search.graphql
packages/client/src/search/index.ts

Let me know If I'm missing anything super obvious here!

feat: client SDK - add search module

---

.changeset/brown-geese-whisper.md
.changeset/cyan-nails-turn.md
.changeset/fifty-rings-kiss.md
.changeset/kind-forks-applaud.md
.changeset/plenty-kings-sneeze.md
.changeset/short-starfishes-collect.md
packages/api-bindings/CHANGELOG.md
packages/api-bindings/package.json
packages/blockchain-bindings/CHANGELOG.md
packages/blockchain-bindings/package.json
packages/client/CHANGELOG.md
packages/domain/CHANGELOG.md
packages/domain/package.json
packages/eslint-config/CHANGELOG.md
packages/eslint-config/package.json
packages/prettier-config/CHANGELOG.md
packages/prettier-config/package.json
packages/react/CHANGELOG.md
packages/react/package.json
packages/sdk-gated/CHANGELOG.md
packages/shared-kernel/CHANGELOG.md
packages/shared-kernel/package.json
packages/storage/CHANGELOG.md
packages/storage/package.json
packages/wagmi/CHANGELOG.md
packages/wagmi/package.json

release #4

---

packages/client/README.md
packages/client/TODO.md
packages/client/src/LensClient.spec.ts
packages/client/src/LensClient.ts
packages/client/src/authentication/Authentication.ts
packages/client/src/explore/Explore.spec.ts
packages/client/src/explore/Explore.ts
packages/client/src/helpers/execute.ts
packages/client/src/reactions/Reactions.ts
packages/client/src/search/Search.spec.ts
packages/client/src/search/Search.ts

- unify auth interface (`IAuthentication`), 
- add `execute` helper for API calls that require authentication 
- search and explore modules improvements - correct method names and return values

feat: client sdk - unify auth interface, add execute helper, search and explore modules improvements

---

packages/client/TODO.md
packages/client/src/LensClient.spec.ts
packages/client/src/LensClient.ts
packages/client/src/index.ts
packages/client/src/modules/Modules.spec.ts
packages/client/src/modules/Modules.ts
packages/client/src/modules/graphql/modules.generated.ts
packages/client/src/modules/graphql/modules.graphql
packages/client/src/modules/index.ts

- client.modules.fetchEnabledCurrencies()
- client.modules.fetchEnabled()
- client.modules.approvedAllowanceAmount(request)
- client.modules.generateCurrencyApprovalData(request)

feat: client sdk - add modules

---

examples/web-wagmi/src/App.tsx
examples/web-wagmi/src/components/auth/LoginButton.tsx
examples/web-wagmi/src/misc/LoginSpecificProfile.tsx
examples/web-wagmi/src/misc/MiscPage.tsx
packages/domain/package.json
packages/domain/src/use-cases/lifecycle/Bootstrap.ts
packages/domain/src/use-cases/lifecycle/__tests__/Bootstrap.spec.ts
packages/domain/src/use-cases/profile/ActiveProfileLoader.ts
packages/domain/src/use-cases/profile/IActiveProfileGateway.ts
packages/domain/src/use-cases/profile/__tests__/ActiveProfileLoader.spec.ts
packages/domain/src/use-cases/wallets/WalletLogin.ts
packages/domain/src/use-cases/wallets/__tests__/WalletLogin.spec.ts
packages/react/src/lifecycle/adapters/useBootstrapController.ts
packages/react/src/wallet/useWalletLogin.ts

@desfero Saw your comments on the other PR and wanted to get some feedback before fixing tests, adding examples and cleaning up. Let me know what you think!

Add a way to log into a specific profile by handle

---

packages/client/src/helpers/buildPaginatedQueryResult.spec.ts
packages/client/src/search/Search.ts
packages/client/src/search/graphql/search.generated.ts
packages/client/src/search/graphql/search.graphql

context discussion https://github.com/dotansimha/graphql-code-generator/discussions/5567

chore: handle search result empty types after graphql-codegen upgrade

---

.changeset/chatty-poems-invent.md
examples/web-wagmi/src/profiles/UseCreateProfile.tsx
packages/react/src/__tests__/helpers.spec.ts
packages/react/src/profile/index.ts
packages/react/src/profile/useProfilesOwnedByMe.tsx
packages/react/src/shared.tsx
packages/react/src/transactions/adapters/responders/CreateProfileResponder.ts

Docs: https://dash.readme.com/project/lensprotocol/v1.1/docs/use-profiles-owned-by-me

`useProfilesOwnedBy` should be updated as new profile is created

---

packages/client/TODO.md
packages/client/src/LensClient.spec.ts
packages/client/src/LensClient.ts
packages/client/src/index.ts
packages/client/src/nfts/Nfts.spec.ts
packages/client/src/nfts/Nfts.ts
packages/client/src/nfts/graphql/nfts.generated.ts
packages/client/src/nfts/graphql/nfts.graphql
packages/client/src/nfts/index.ts
packages/client/src/nonces/Nonces.spec.ts
packages/client/src/profile/Profile.spec.ts
packages/client/src/publication/Publication.spec.ts
packages/client/src/stats/Stats.spec.ts

client.nfts.fetch(request)
client.nfts.ownershipChallenge(request)
+ all nft gallery queries and mutations

feat: client sdk - add nfts module

---

packages/api-bindings/src/graphql/generated.tsx
packages/api-bindings/src/graphql/notification.graphql
packages/react/src/notifications/index.ts
packages/react/src/notifications/useNotifications.ts

Looks like we need this functionality elsewhere!

Add notification type filter to useNotifications hook

---

packages/client/src/profile/Profile.ts

I found a bug in the client sdk

bugfix: client sdk - createSetProfileImageURIViaDispatcher

---

.changeset/twenty-icons-buy.md
packages/domain/src/use-cases/publications/CreateComment.ts
packages/domain/src/use-cases/publications/CreatePost.ts
packages/react/src/LensProvider.tsx
packages/react/src/__tests__/config.spec.ts
packages/react/src/config.ts
packages/react/src/shared.tsx
packages/react/src/transactions/adapters/PendingTransactionGateway/schema/publications.ts
packages/react/src/transactions/infrastructure/__tests__/createPublicationMetadata.spec.ts
packages/react/src/transactions/infrastructure/createPublicationMetadata.ts
packages/react/src/transactions/useCreateComment.ts
packages/react/src/transactions/useCreateEncryptedComment.ts
packages/react/src/transactions/useCreateEncryptedPost.ts
packages/react/src/transactions/useCreatePost.ts

example metadata with appId created with web-wagmi example app
https://co2e35tifh3htlkrjewg77qsfurkvdopte2lcwtztkksaolzileq.arweave.net/E7RN9mgp9nmtUUksb_4SLSKqjc-ZNLFaeZqVIDl5Qsk

feat: allow to define appId in the LensConfig

---

.changeset/young-beds-sniff.md
packages/client/src/authentication/adapters/AuthenticationApi.ts
packages/client/src/explore/Explore.ts
packages/client/src/feed/Feed.ts
packages/client/src/graphql/FetchGraphQLClient.ts
packages/client/src/helpers/requireAuthHeaders.ts
packages/client/src/modules/Modules.ts
packages/client/src/nfts/Nfts.ts
packages/client/src/nonces/Nonces.ts
packages/client/src/notifications/Notifications.ts
packages/client/src/profile/Profile.ts
packages/client/src/proxy-action/ProxyAction.ts
packages/client/src/publication/Publication.ts
packages/client/src/reactions/Reactions.ts
packages/client/src/revenue/Revenue.ts
packages/client/src/search/Search.ts
packages/client/src/stats/Stats.ts
packages/client/src/transaction/Transaction.ts
packages/client/src/types/fetch.d.ts
pnpm-lock.yaml

fixes https://github.com/lens-protocol/lens-sdk/issues/285

feat: client sdk - use fetch with graphql

---

.github/workflows/ci.yaml

```yml
node-version-file: '.nvmrc'
cache: 'pnpm'
```
This will improve the CI speed

chore(ci): use node version from .nvmrc and enable cache

---

.changeset/silly-yaks-run.md

Forgot in previous PRs before merging.

Adds Momoka support changeset

---

.changeset/thirty-hornets-itch.md
examples/node/scripts/authenticate.ts
packages/client/src/authentication/Authentication.spec.ts
packages/client/src/authentication/Authentication.ts

solves https://github.com/lens-protocol/lens-sdk/issues/252

feat: add verify and getAccessToken methods

---

packages/gated-content/environments/package.json
packages/gated-content/package.json
packages/gated-content/src/environments.ts
packages/react/src/environments.ts
packages/react/src/index.ts
packages/react/src/transactions/infrastructure/createGatedClient.ts

feat: supports arbitrary environments

---

examples/node/scripts/nfts.ts

I was helping someone on discord and created this script as an example usage of LensClient and nfts submodule, I'd like to add it to the library of LensClient scripts

chore: add script to show how to use lens client to manage nft galleries

---

.changeset/kind-pants-double.md
.changeset/mighty-drinks-roll.md
.changeset/poor-points-jog.md
.changeset/sharp-baboons-chew.md
examples/web-wagmi/src/publications/UsePublication.tsx
examples/web-wagmi/src/publications/components/PublicationComments.tsx
packages/api-bindings/src/apollo/cache/createProfilesFieldPolicy.ts
packages/api-bindings/src/apollo/cache/createPublicationsFieldPolicy.ts
packages/api-bindings/src/lens/generated.ts
packages/api-bindings/src/lens/publications.graphql
packages/domain/src/use-cases/publications/CreateComment.ts
packages/domain/src/use-cases/publications/CreatePost.ts
packages/domain/src/use-cases/publications/types.ts
packages/react/src/helpers/arguments.ts
packages/react/src/publication/index.ts
packages/react/src/publication/useComments.ts
packages/react/src/publication/useExplorePublications.ts
packages/react/src/transactions/adapters/schemas/__tests__/validators.spec.ts
packages/react/src/transactions/adapters/schemas/publications.ts
packages/react/src/transactions/infrastructure/__tests__/createPublicationMetadata.spec.ts
packages/react/src/transactions/infrastructure/createPublicationMetadata.ts
packages/react/src/transactions/useCreateComment.ts
packages/react/src/transactions/useCreatePost.ts

fix: misc issues reported

---

examples/node/scripts/feed/forYou.ts
examples/node/scripts/publication/reactions/fetch.ts
packages/client/codegen-api.yml
packages/client/src/graphql/fragments.generated.ts
packages/client/src/graphql/fragments.graphql
packages/client/src/graphql/types.generated.ts
packages/client/src/submodules/feed/Feed.ts
packages/client/src/submodules/feed/graphql/feed.generated.ts
packages/client/src/submodules/feed/graphql/feed.graphql
packages/client/src/submodules/momoka/graphql/momoka.generated.ts
packages/client/src/submodules/momoka/graphql/momoka.graphql
packages/client/src/submodules/nfts/graphql/nfts.generated.ts
packages/client/src/submodules/nfts/graphql/nfts.graphql
packages/client/src/submodules/publication/graphql/publication.generated.ts
packages/client/src/submodules/publication/graphql/publication.graphql
packages/client/src/submodules/publication/submodules/reactions/Reactions.ts
packages/client/src/submodules/publication/submodules/reactions/graphql/reactions.generated.ts
packages/client/src/submodules/publication/submodules/reactions/graphql/reactions.graphql

PoapEventId scalar, mirrorOf renaming to mirrorOn, globalReach removal, forYou removal, encryptable metadata fixes, Video/Audio/Image fixes, quotedOn typo fix

Fix lens-api v2 breaking changes 

---

.github/workflows/docs.yaml

With this workflow we would be able to generate new documentation after a merge is approved.

Adding automatic update of documentation

---

.changeset/happy-donuts-boil.md
examples/web/src/App.tsx
examples/web/src/misc/MiscPage.tsx
examples/web/src/misc/UseInviteWallets.tsx
examples/web/src/misc/index.ts
packages/api-bindings/src/lens/graphql/generated.ts
packages/api-bindings/src/lens/graphql/invites.graphql
packages/client/src/submodules/invites/Invites.ts
packages/client/src/submodules/invites/graphql/invites.generated.ts
packages/domain/src/entities/Invite.ts
packages/domain/src/entities/index.ts
packages/domain/src/use-cases/wallets/InviteWallets.ts
packages/domain/src/use-cases/wallets/index.ts
packages/react/src/misc/adapters/InviteWalletsGateway.ts
packages/react/src/misc/adapters/InviteWalletsPresenter.ts
packages/react/src/misc/adapters/useInviteWalletsController.ts
packages/react/src/misc/index.ts
packages/react/src/misc/useInviteWallets.ts
packages/react/src/misc/useInvitedProfiles.ts
packages/react/src/misc/useWasWalletInvited.ts

- useInvitedProfiles
- useWasWalletInvited + useLazyWasWalletInvited
- useInviteWallets

feat: add invite hooks

---

.changeset/strange-yaks-sit.md
examples/node/scripts/authentication/upgradeCredentials.ts
packages/client/src/authentication/Authentication.ts
packages/client/src/authentication/IAuthentication.ts
packages/client/src/authentication/adapters/AuthenticationApi.ts
packages/client/src/authentication/graphql/auth.generated.ts
packages/client/src/authentication/graphql/auth.graphql
packages/client/src/graphql/index.ts
packages/client/src/graphql/types.generated.ts
packages/client/src/submodules/poaps/graphql/poap.generated.ts

client: add upgradeCredentials method

---

.changeset/cuddly-emus-judge.md
packages/domain/src/use-cases/profile/UnfollowProfile.ts
packages/domain/src/use-cases/profile/__helpers__/mocks.ts
packages/react/src/transactions/adapters/profiles/UnfollowProfileGateway.ts
packages/react/src/transactions/adapters/profiles/__tests__/UnfollowProfileGateway.spec.ts
packages/react/src/transactions/adapters/schemas/profiles.ts
packages/react/src/transactions/adapters/useUnfollowController.ts
packages/react/src/transactions/useUnfollow.ts

- feat: adds self-funded support for unfollow
- chore: changeset

feat: adds self-funded support for unfollow

---

.changeset/curvy-birds-juggle.md
packages/client/src/authentication/Authentication.ts
packages/client/src/index.ts
packages/client/src/submodules/explore/Explore.ts
packages/client/src/submodules/feed/Feed.ts
packages/client/src/submodules/handle/Handle.ts
packages/client/src/submodules/invites/Invites.ts
packages/client/src/submodules/modules/Modules.ts
packages/client/src/submodules/momoka/Momoka.ts
packages/client/src/submodules/nfts/Nfts.ts
packages/client/src/submodules/notifications/Notifications.ts
packages/client/src/submodules/poaps/Poaps.ts
packages/client/src/submodules/profile/Profile.ts
packages/client/src/submodules/publication/Publication.ts
packages/client/src/submodules/publication/submodules/actions/Actions.ts
packages/client/src/submodules/publication/submodules/bookmarks/Bookmarks.ts
packages/client/src/submodules/publication/submodules/notInterested/NotInterested.ts
packages/client/src/submodules/publication/submodules/reactions/Reactions.ts
packages/client/src/submodules/revenue/Revenue.ts
packages/client/src/submodules/search/Search.ts
packages/client/src/submodules/transaction/Transaction.ts
packages/client/src/submodules/wallet/Wallet.ts
packages/client/typedoc.json

exclude constructors and other internal methods from docs

client: mark poaps and nfts as experimental

---

.changeset/good-insects-compete.md
packages/api-bindings/src/lens/__helpers__/fragments.ts
packages/api-bindings/src/lens/graphql/fragments.graphql
packages/client/src/graphql/fragments.generated.ts
packages/client/src/graphql/fragments.graphql
packages/client/src/graphql/index.ts
packages/client/src/submodules/explore/graphql/explore.generated.ts
packages/client/src/submodules/feed/graphql/feed.generated.ts
packages/client/src/submodules/invites/graphql/invites.generated.ts
packages/client/src/submodules/nfts/graphql/nfts.generated.ts
packages/client/src/submodules/notifications/graphql/notifications.generated.ts
packages/client/src/submodules/poaps/graphql/poap.generated.ts
packages/client/src/submodules/profile/graphql/profile.generated.ts
packages/client/src/submodules/publication/graphql/publication.generated.ts
packages/client/src/submodules/publication/submodules/bookmarks/graphql/bookmarks.generated.ts
packages/client/src/submodules/publication/submodules/reactions/graphql/reactions.generated.ts
packages/client/src/submodules/revenue/graphql/revenue.generated.ts
packages/client/src/submodules/search/graphql/search.generated.ts
packages/client/src/submodules/wallet/graphql/wallet.generated.ts

- `lensClassifierScore` on ProfileStats
- `collectNft` on all relevant OpenActionSettings
- `isEncrypted`, `profilesMentioned` and `hashtagsMentioned` on Post, Comment and Quote

feat: add new fields on fragments

---

.changeset/shy-tomatoes-jump.md
packages/client/src/graphql/index.ts
packages/client/src/graphql/types.generated.ts
packages/client/src/submodules/feed/Feed.ts
packages/client/src/submodules/feed/graphql/feed.generated.ts
packages/client/src/submodules/feed/graphql/feed.graphql
packages/client/src/submodules/feed/index.ts
packages/client/src/submodules/feed/types.ts

link https://github.com/lens-protocol/lens-sdk/pull/907

client: latestPaidActions accepts optional request arguments
